steps:
# Build the container image
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/$flaskhelloworldapp1-339218/flaskhelloworldapp1 	', '.']
# Push the container image to Container Registry
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/$flaskhelloworldapp1-339218/flaskhelloworldapp1 	']
# Deploy container image to Cloud Run
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  entrypoint: gcloud
  args: ['run', 'deploy', '$flaskhelloworldapp1 	', '--image', 'gcr.io/$flaskhelloworldapp1-339218/flaskhelloworldapp1 	', '--region', 'us-central1', '--platform', 'managed','--port','80']
images:
- gcr.io/$flaskhelloworldapp1-339218/flaskhelloworldapp1
options:
 logging: CLOUD_LOGGING_ONLY 	